### PR TITLE
fix: remove nodenv, clean up mergeTranslations script, fix "lint" script

### LINKED ISSUE #7: nodenv is causing problems on Windows
The current project template still uses `nodenv` for running the **mergeTranslations.js** script. However, this seems to fail on Windows:

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for nodenv@0.1.0: wanted {"os":"!win32"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  !win32
npm ERR! notsup Actual os: win32
```

(using Node@18.18.0 LTS / NPM@9.8.1)

### PR DESCRIPTION
**Pull request by defaude**
Main target: Remove nodenv ✅

Should Fix #7 

While I was at it, I exchanged the `rm -rf` part that wouldn't be working on Windows, anyway, with `rimraf`

I cleaned up and modernized the `mergeTranslations` script quite a bit (I guess the original version comes from a time before node even had the `fs/promises` APIs...)

And I found that running `npm run lint` didn't work properly, as well - so I fixed that

### CODE REVIEW

File: template/mergeTranslations.js [hunk 1]
```diff
@@ -1,58 +1,35 @@
...
+    }
+    map.get(locale).push(file);
+    return map;
+}, new Map());
 
-const mergeByLocale = async (locale, localesMap) => {
-    const filesToMerge = localesMap.get(locale);
-    const mergedContent = await Promise.all(filesToMerge.map(getJsonFileContent));
+// merge all files belonging to the same locale
+for (const [locale, files] of filesByLocales) {
```
Comment (rkipsch) [inline template/mergeTranslations.js:25]: Is there any reason for not using functional style here and mapping over it? At least, it would be consistent style with the functions.

File: template/mergeTranslations.js [hunk 2]
```diff
@@ -1,58 +1,35 @@
...
 
-const writeFile = (filePath, content) =>
-    new Promise((resolve, reject) => fs.writeFile(filePath, content, 'utf8', err => (err ? reject(err) : resolve())));
+// list all files in temp folder
+const allTempFiles = await readdir(tempDir);
 
-const getJsonFileContent = async file => JSON.parse(await readFile(`${tempDir}/${file}`));
+// collect files for each locale
+const filesByLocales = allTempFiles.reduce((map, file) => {
+    const locale = file.split('.')[1];
```
Comment (rkipsch) [inline template/mergeTranslations.js:16]: We could also write
`const [, locale] = file.split('.');`

File: template/package.json [hunk 3]
```diff
@@ -11,13 +12,13 @@
...
         "coverage": "vitest run --coverage",
-        "lint": "eslint src",
+        "lint": "eslint src --ext .js,.jsx,.ts,.tsx",
         "lint-fix": "npm run lint -- --fix",
         "audit": "npm audit --production --registry https://registry.npmjs.org --parseable",
         "format-code": "prettier --write \"src/**/*.{js,jsx,ts,tsx,json,css,scss,md}\"",
         "format-code-on-commit": "npm run format-code && git add",
         "pull-translations": "phrase pull --access_token $PHRASEAPP_ACCESS_TOKEN && npm run merge-translations",
-        "merge-translations": "nodenv ./mergeTranslations.js",
+        "merge-translations": "node mergeTranslations.js && rimraf src/features/translations/temp",
```
Comment (rkipsch) [inline template/package.json:21]: Hmm, we could move the cleanup of the temp folder into the merge script itself to have everything together. We would not need an additional library too and keep the dependencies to a minimum.

File: template/mergeTranslations.js (hunk 1 above)
Comment (defaude) [reply template/mergeTranslations.js:25]: My reasoning was "hey, we're using a `Map`, after all, so we can utilitze a nice `for ... of` (less function context overhead). But just as Linkin Park said: "But in the end, it doesn't even matter".

File: template/mergeTranslations.js (hunk 2 above)
Comment (rkipsch) [reply template/mergeTranslations.js:16]: This is exactly why this shorthand was invented :-) The rest of the script is already elegant except for this ;-)

File: template/mergeTranslations.js (hunk 1 above)
Comment (rkipsch) [reply template/mergeTranslations.js:25]: hehe, I like LP. I would just want to keep a consistent style.

File: template/package.json (hunk 3 above)
Comment (defaude) [reply template/package.json]: I updated the script so that it performs the deletion of the `temp` directory and dropped the `rimraf` dependency again.

File: template/mergeTranslations.js (hunk 2 above)
Comment (defaude) [reply template/mergeTranslations.js]: Updated :D

File: template/mergeTranslations.js (hunk 1 above)
Comment (defaude) [reply template/mergeTranslations.js:25]: Quote from Robin:

> ich bestehe da nicht drauf :D
